[build]
publish = "public"
command = "sh update-map.sh && hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"


[context.branch-deploy.environment]
HUGO_VERSION = "0.48"
